version: '3'
services:
  server:
    build:
      context: .
      dockerfile: build/server/Dockerfile
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    build:
      context: build/db
      dockerfile: Dockerfile
    volumes:
      - ./build/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
